/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConnectionChip: typeof import('./components/ConnectionChip.vue')['default']
    Errors: typeof import('./components/Errors.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    SQLInput: typeof import('./components/SQLInput.vue')['default']
  }
}
