name: Lint Go Code

on:
  push:
  workflow_dispatch: # Allows manual triggering

jobs:
  lint-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
